version: '3'
services:
   nginx:
       image: nginx:latest
       container_name: nginx
       volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf:ro
       ports:
          - 8050:8050
          - 443:443